#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=04:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2025
module load Anaconda3/2025.06-1

cd $HOME/human-centered-ml/
conda env remove -n deepAL
conda env create -f environment.yml
source activate deepAL
python -c "import numpy; print(f'Numpy version: {numpy.__version__}')"